### ISSUE TITLE
Crash on Android version 4.1

### ISSUE THREAD

**Issue by matejhacin** [braintree/android-card-form#14]
App crashes when user enters card number and selects expiration date field.

I assume that the date picker is not supported in 4.1? It works on newer versions.

Is this a known issue? Let me know if I should post a stacktrace.

**Comment by lkorth** [comment]
It should work on 4.1. Please post the stacktrace.

**Comment by ramadeef** [comment]
I got same issue. here is log cat
FATAL EXCEPTION: main
                  android.view.InflateException: Binary XML file line #1: Error inflating class TextView
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:466)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                      at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371)
                      at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
                      at com.braintreepayments.cardform.utils.ExpirationDateItemAdapter.getView(ExpirationDateItemAdapter.java:75)
                      at android.widget.AbsListView.obtainView(AbsListView.java:2271)
                      at android.widget.GridView.onMeasure(GridView.java:1046)
                      at android.view.View.measure(View.java:15323)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1421)
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:698)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:579)
                      at android.view.View.measure(View.java:15323)
                      at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1037)
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:581)
                      at android.view.View.measure(View.java:15323)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:315)
                      at android.view.View.measure(View.java:15323)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:315)
                      at android.view.View.measure(View.java:15323)
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924)
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:315)
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2155)
                      at android.view.View.measure(View.java:15323)
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1854)
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1102)
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1275)
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4218)
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                      at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                      at android.view.Choreographer.doFrame(Choreographer.java:525)
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                      at android.os.Handler.handleCallback(Handler.java:615)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4744)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x12
                      at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:463)
                      at android.view.View.<init>(View.java:3354)
                      at android.widget.TextView.<init>(TextView.java:455)
                      at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:59)
                      at android.support.v7.widget.AppCompatTextView.<init>(AppCompatTextView.java:55)
                      at android.support.v7.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
                      at android.support.v7.app.AppCompatDelegateImplV9.createView(AppCompatDelegateImplV9.java:1013)
                      at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:1072)
                      at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:44)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:675)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:466) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:396) 
                      at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:371) 
                      at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362) 
                      at com.braintreepayments.cardform.utils.ExpirationDateItemAdapter.getView(ExpirationDateItemAdapter.java:75) 
                      at android.widget.AbsListView.obtainView(AbsListView.java:2271) 
                      at android.widget.GridView.onMeasure(GridView.java:1046) 
                      at android.view.View.measure(View.java:15323) 
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924) 
                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1421) 
                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:698) 
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:579) 
                      at android.view.View.measure(View.java:15323) 
                      at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1037) 
                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:581) 
                      at android.view.View.measure(View.java:15323) 
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924) 
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:315) 
                      at android.view.View.measure(View.java:15323) 
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924) 
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:315) 
                      at android.view.View.measure(View.java:15323) 
                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4924) 
                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:315) 
                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2155) 
                      at android.view.View.measure(View.java:15323) 
                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1854) 
                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1102) 
                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1275) 
                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000) 
                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4218) 
                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725) 
                      at android.view.Choreographer.doCallbacks(Choreographer.java:555) 
                      at android.view.Choreographer.doFrame(Choreographer.java:525) 
                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711) 
                      at android.os.Handler.handleCallback(Handler.java:615) 
                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4744) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511)

**Comment by ramadeef** [comment]
Android jelly bean sony xperia P version

**Comment by matejhacin** [comment]
@lkorth Sorry for not posting stacktrace earlier. But now @ramadeef posted it anyway. I've got the exact same stacktrace.

**Comment by lkorth** [comment]
Thanks for the report @matejhacin and @ramadeef. I've fixed the crash and pushed it to `master`.

**Comment by lkorth** [comment]
This fix also just went out in `3.0.1`

**Comment by androidqasim** [comment]
how can i solve this issue.
I am working on a project and google developer console reported me about the crash on TextView on Samsung S III device

**Comment by lkorth** [comment]
@androidqasim: it was fixed in 3.0.1, what version are you using that is encountering this crash?

**Comment by matejhacin** [comment]
Thanks @lkorth
