### ISSUE TITLE
rendering and Logcat errors

### ISSUE THREAD

**Issue by Theocom** [braintree/android-card-form#21]
Hi, i receive errors in both my implementation (Card form in a fragment) and in the Demo app. Should i add something more, or just ignore them (the form works and i can initiate Sandbox transactions) ? The errors are in the Design XML View and with error messages:

1. My implementation: no Activity Theme defined , only Application AppTheme , Nexus 4 emulator , API 22 , compiled in API 25

Exception Details : same as below

2. Demo app Theme.Holo.Light: 

The following classes could not be instantiated:
- com.braintreepayments.cardform.view.MobileNumberEditText 
- com.braintreepayments.cardform.view.CardForm 
- android.support.design.widget.TextInputLayout 

 Exception Details java.lang.RuntimeException: Stub!   
at android.telephony.PhoneNumberFormattingTextWatcher.<init>(PhoneNumberFormattingTextWatcher.java:21)   
at com.braintreepayments.cardform.view.MobileNumberEditText.init(MobileNumberEditText.java:37)   
at com.braintreepayments.cardform.view.MobileNumberEditText.<init>(MobileNumberEditText.java:25)   
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.inflate(LayoutInflater.java:492)   
at android.view.LayoutInflater.inflate(LayoutInflater.java:397)   
at android.view.View.inflate(View.java:20841)   
at com.braintreepayments.cardform.view.CardForm.init   ... (CardForm.java:98)   
at com.braintreepayments.cardform.view.CardForm.<init>(CardForm.java:80)   
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)   
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:858)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   
at android.view.LayoutInflater.rInflate_Original(LayoutInflater.java:861)   
at android.view.LayoutInflater_Delegate.rInflate(LayoutInflater_Delegate.java:70)   
at android.view.LayoutInflater.rInflate(LayoutInflater.java:834)   
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)   
at android.view.LayoutInflater.inflate(LayoutInflater.java:518)   
at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
Copy stack to clipboard   Failed to find style 'editTextStyle' in current theme (48 similar errors not shown)

3. After closing the Demo app, i get a notification "LightThemeActivity has leaked"

4. When the Message "Card number is invalid" pops up :
E/AppCompatResources: Failed to inflate ColorStateList, leaving it to the framework
java.lang.RuntimeException: Failed to resolve attribute at index 0
at android.content.res.TypedArray.getColor(TypedArray.java:401)
at android.support.v7.content.res.AppCompatColorStateListInflater.inflate(AppCompatColorStateListInflater.java:114)
... and so on

**Comment by sdcoffey** [comment]
Hey @Theocom, 

Sorry about the delay in responding to your issue! The `Stub!` indicates that the jar containing the implementations for the methods that are being called aren't present. This could occur because you're running unit tests (which run in the JVM), or there's something otherwise fishy about your setup. Are you using Android Studio with Gradle for this project?

**Comment by Theocom** [comment]
Hi, Steve

Yes , i use Android studio 2.2.3 with the latest Gradle plugin with Gradle 2.14.1 . Compiled with SDK 25 , build tools 25.0.2
compile 'com.braintreepayments.api:braintree:2.3.12'
compile 'com.braintreepayments:card-form:3.0.2'

The sample Simplify app gives me similar rendering errors with their cart:

The following classes could not be instantiated:
- com.simplify.android.sdk.CardEditor

java.lang.ClassNotFoundException: rx.Single$OnSubscribe  
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)  
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)  
at com.simplify.android.sdk.CardEditor.init   ... (CardEditor.java:248)  
at com.simplify.android.sdk.CardEditor.<init>(CardEditor.java:91)  
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)  
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
... and so on

As for now, i'm simply ignoring the rendering errors, because the cart layout works as expected


----- Original Nachricht ----
Von:     Steve Coffey <notifications@github.com>
An:      braintree/android-card-form <android-card-form@noreply.github.com>
Datum:   29.12.2016 17:39
Betreff: Re: [braintree/android-card-form] rendering and Logcat errors (#21)

**Comment by sdcoffey** [comment]
Ok! Let us know if you have any issues with the card form itself. Thanks!
