### ISSUE TITLE
Crash at CardType.validate() for Android 8.0.0

### ISSUE THREAD

**Issue by deandalm** [braintree/android-card-form#62]
### General information

* SDK/Library version: card-form:3.5.0
* Android Version and Device: Galaxy S7 Edge with Android 8.0.0 and SM-J337P with Android 8.0.0

### Issue description
Crash reported by Crashylitcs but haven't both able to reproduce locally.

### Stacktrace
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.regex.Matcher java.util.regex.Pattern.matcher(java.lang.CharSequence)' on a null object reference
       at com.braintreepayments.cardform.utils.CardType.validate(CardType.java:223)
       at com.silvercar.mobi.ui.view.CardEditText.isValid(CardEditText.java:120)
       at com.silvercar.mobi.ui.view.CardForm.isCardNumberValid(CardForm.java:161)
       at com.silvercar.mobi.ui.account.CreditCardActivity.isCreditCardValid(CreditCardActivity.java:268)
       at com.silvercar.mobi.ui.account.CreditCardActivity.finishSubmission(CreditCardActivity.java:256)
       at com.silvercar.mobi.ui.account.CreditCardActivity.onFinishClicked(CreditCardActivity.java:238)
       at com.silvercar.mobi.ui.account.CreditCardActivity_ViewBinding$8.doClick(CreditCardActivity_ViewBinding.java:135)
       at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
       at android.view.View.performClick(View.java:6897)
       at android.widget.TextView.performClick(TextView.java:12693)
       at android.view.View$PerformClick.run(View.java:26100)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by deandalm** [comment]
@quinnjn awesome, any ETA on a release?

**Comment by quinnjn** [comment]
Released [3.5.1](https://github.com/braintree/android-card-form/releases/tag/3.5.1) which includes this change.
