### ISSUE TITLE
CASTING ERROR

### ISSUE THREAD

**Issue by gregcho** [braintree/android-card-form#99]
Dear
It is really good app for me.
but I have some trouble this with my app

trouble is below. 

Process: org.tensorflow.lite.examples.detection, PID: 3511
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.tensorflow.lite.examples.detection/org.tensorflow.lite.examples.detection.LightThemeActivity}: java.lang.ClassCastException: com.braintreepayments.cardform.view.SupportedCardTypesView cannot be cast to com.braintreepayments.cardform.view.CardForm
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3654)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
     Caused by: java.lang.ClassCastException: com.braintreepayments.cardform.view.SupportedCardTypesView cannot be cast to com.braintreepayments.cardform.view.CardForm
        at org.tensorflow.lite.examples.detection.BaseCardFormActivity.onCreate(BaseCardFormActivity.java:36)
        at android.app.Activity.performCreate(Activity.java:7963)
        at android.app.Activity.performCreate(Activity.java:7952)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3629)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3806) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:237) 
        at android.app.ActivityThread.main(ActivityThread.java:8167) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by sshropshire** [comment]
Hi @gregcho which version of `card-form` are you using?

Also, is your app performing the cast? It's difficult to tell from the stack trace since we also have a class named `BaseCardFormActivity`.

**Comment by sarahkoop** [comment]
Hi @gregcho - Are you still experiencing this issue? If so, are you able to provide the above requested information?

**Comment by sarahkoop** [comment]
Closing this issue due to inactivity. Please feel free to re-open if you are still experiencing this and are able to provide the requested information.
